<a href="https://colab.research.google.com/github/MiguelAngelTinocoArroyo/Python/blob/main/Resueltos/Problema_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 7. Escribir una función que dada una matriz, escriba una función
# para mover todos los ceros al final mientras mantiene el orden 
# relativo de los elementos distintos de cero.

import numpy as np

A = np.array([[1,9,0],[6,5,4],[1,6,0],[5,0,4]])

def MoverCerosFinalMatriz(A):
    lista = []
    contador = 0
    for i in range(A.shape[0]): 
        for j in range(A.shape[1]):
            if A[i][j] != 0:
                lista.append(A[i][j])
                
    dimen_A = A.shape[0]*A.shape[1]
    
    while len(lista) < dimen_A:
            lista.append(0)
           
    for i in range(A.shape[0]): 
        for j in range(A.shape[1]):
            A[i][j] = lista[contador] 
            contador += 1              
    return A

print(MoverCerosFinalMatriz(A))

[[1 9 6]
 [5 4 1]
 [6 5 4]
 [0 0 0]]
